### ISSUE TITLE
 Cannot find module 'aws-sdk' when trying to use only gcs driver

### ISSUE THREAD

**Issue by ojhaujjwal** [Slynova-Org/flydrive#134]
I am trying use this package with just the gcs driver and I am getting aws sdk not found error. There must be some way to allow the package users to use the package without installing all the dependencies.
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/4995501/80910885-502a3700-8d52-11ea-8584-229c02b4a3cb.png">

**Comment by targos** [comment]
I think there are only two solutions if we want to keep the drivers in this package:
- add `aws-sdk` and `@google-cloud/storage` to the dependencies. I don't really like this because it adds unnecessary dependencies to people who do not use the drivers.
- document that the users should add `"skipLibCheck": true` to their tsconfig.

Any other idea?

**Comment by ojhaujjwal** [comment]
I am not sure if this helps; but I am checking out how nestjs does it.
Check this out
https://github.com/nestjs/nest/blob/master/packages/common/serializer/class-serializer.interceptor.ts#L10 
and https://github.com/nestjs/nest/blob/master/packages/common/serializer/class-serializer.interceptor.ts#L24-L29

**Comment by RomainLanz** [comment]
Hey @ojhaujjwal! 👋 

We are removing drivers from the core's package.
Therefore, you'll install only the driver you need and you will have no error about other drivers.

I'll let you know when it's released.

**Comment by ojhaujjwal** [comment]
That's great news @RomainLanz.
Please let know when that's done :)

**Comment by RomainLanz** [comment]
Should be all good now. 😄
