### ISSUE TITLE
Add createWriteStream() method support

### ISSUE THREAD

**Issue by rijkvanzanten** [Slynova-Org/flydrive#149]
We already have `getStream`, but that only returns a readable stream for the file:

https://github.com/Slynova-Org/flydrive/blob/207ced0c808c633428d19850bdaf7edd015f49bb/packages/flydrive/src/LocalFileSystemStorage.ts#L144-L149

By having a way to retrieve a write stream, you can easily pipe the output of another stream (like file manipulation) to disk. For example, I'd like to read a file from S3, transform it using Sharp, and immediately stream it back up to a new file:

```ts
const originalFile = 'foo.jpg';
const thumb = 'bar.jpg';

const transformer = sharp().resize(200, 250);

const readStream = storage.disk('local').getStream(originalFile);
const writeStream = storage.disk('local').createWriteStream(thumb);

readStream.pipe(transformer).pipe(writeStream);
```

**Comment by targos** [comment]
The `put` method already accepts a readable stream and will automatically open en writable stream and pipe to it.
Is that enough for your use case?

Edit: should look like this with the current API:

```js
const originalFile = 'foo.jpg';
const thumb = 'bar.jpg';

const transformer = sharp().resize(200, 250);

const readStream = storage.disk('local').getStream(originalFile);
const writeStream = storage.disk('local').createWriteStream(thumb);

await storage.disk('local').put(readStream.pipe(transformer));
```

It's more powerful than manual piping because it handles errors and closes streams correctly (with `stream.pipeline`) and creates missing directories if necessary.

**Comment by rijkvanzanten** [comment]
Thanks @targos! This does indeed solve for my particular use case. 👍
