### ISSUE TITLE
Does support for making directories exist?

### ISSUE THREAD

**Issue by barkdoll** [Slynova-Org/flydrive#160]
Hi flydrive folks,

I am in need of a package like flydrive, and I have been reviewing the repository's docs. It has a lot of awesome features, but I was wondering—  is there a way within the API to create empty directories? Great work on the project!

**Comment by targos** [comment]
There is no direct support for making directories because it is not a portable operation between drivers. I don't know about AWS S3, but Google Cloud Storage and Azure Blob Storage do not have the concept of individual directories. It's just file names with slashes in them.

Note that methods that create files are supposed to automatically create directories. If some don't, it's a bug.

**Comment by barkdoll** [comment]
@targos I see. I had a feeling that was their philosophy and hence, they eliminate that way of thinking in the API altogether. Thanks for clearing that up!
